# @see https://yarnpkg.com/configuration/yarnrc

# Compression level employed for zip archives (See documentation for details)
compressionLevel: mixed

# Define whether the cache should be shared between all local projects (See documentation for details).
enableGlobalCache: false

# Define how Node packages should be installed (See documentation for details).
nodeLinker: node-modules

# Define whether to reuse most common dependency ranges or not when adding dependencies to a package (See documentation for details).
preferReuse: true
