# fly.toml app configuration file generated for ticketmaster-scrapper on 2025-01-18T17:09:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ticketmaster-scrapper'
primary_region = 'fra'

[build]
image = "sdevilcry/ticketmaster_scrapper:latest"

[[vm]]
  size = 'shared-cpu-1x'

[processes]
app = "node dist/ticketmaster.js"

[deploy]
strategy = "immediate"

[[services]]
processes = [ "app" ]
