name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust if necessary)

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticketmaster_scrapper:latest .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ticketmaster_scrapper:latest

  deploy-ticket-0507:
    name: Deploy Ticket O507
    needs: build-and-push  # Ensures this job only runs if 'build-and-push' succeeds
    uses: ./.github/workflows/deploy.yml
    with:
      fly_app_name: app-ticket-0507
    secrets:
      fly_api_token: ${{ secrets.FLY_APP_0507 }}
      ticketmaster_url: ${{ secrets.TICKET_URL_0507 }}

  deploy-ticket-0607:
    name: Deploy Ticket O607
    needs: build-and-push  # Ensures this job only runs if 'build-and-push' succeeds
    uses: ./.github/workflows/deploy.yml
    with:
      fly_app_name: app-ticket-0607
    secrets:
      fly_api_token: ${{ secrets.FLY_APP_0607 }}
      ticketmaster_url: ${{ secrets.TICKET_URL_0607 }}
