name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust if necessary)

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticketmaster_scrapper:latest .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ticketmaster_scrapper:latest

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures this job only runs if 'build-and-push' succeeds
    concurrency: deploy-group

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Fly.io CLI
      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Step 3: Deploy to Fly.io
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
