name: Scheduled Deploy

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  deploy-ticket-0507:
    uses: ./.github/workflows/deploy.yml
    with:
      fly_config: fly.0507.toml
    secrets:
      fly_api_token: ${{ secrets.FLY_APP_0507 }}

  deploy-ticket-0607:
    uses: ./.github/workflows/deploy.yml
    with:
      fly_config: fly.0607.toml
    secrets:
      fly_api_token: ${{ secrets.FLY_APP_0607 }}
