name: Scheduled Deploy

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Redeploy Fly.io App
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
