name: Scheduled Deploy

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  deploy-ticket-0507:
    uses: ./.github/workflows/deploy.yml
    with:
      fly_app_name: app-ticket-0507
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
      ticketmaster_url: ${{ secrets.TICKET_URL_0507 }}

  deploy-ticket-0607:
    uses: ./.github/workflows/deploy.yml
    with:
      fly_app_name: app-ticket-0607
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
      ticketmaster_url: ${{ secrets.TICKET_URL_0607 }}
